site_name: convtools
theme:
  name: material
        # highlightjs: true
        # hljs_languages:
        #     - python
  custom_dir: docs/overrides
  features:
    - content.code.copy
    - navigation.expand

extra:
  analytics:
    provider: google
    property: G-Q41F2W9QLY

repo_name: westandskif/convtools
repo_url: https://github.com/westandskif/convtools
site_url: https://convtools.readthedocs.io/en/latest/
use_directory_urls: true

nav:
  - Welcome: README.md
  - Usage:
     - Basics: basics.md
     - Collections: collections.md
     - Conditions and Pipes: conditions_n_pipes.md
     - Group By and Aggregate: aggregations.md
     - Joins: joins.md
     - Dates: dates.md
     - Mutations: mutations.md
     - Exceptions: exceptions.md
     - Window functions: window_funcs.md
     - Contrib / Tables: contrib_tables.md
     - Contrib / Fs: contrib_fs.md
  - Benefits: benefits.md
  - Changelog: CHANGELOG.md
  - Breaking changes: BREAKING_CHANGES.md
  - Contributors: contributors.md
  - License: LICENSE.md

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - markdown_include.include:
      base_path: docs
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition:
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.inlinehilite:
  - pymdownx.superfences:
  - pymdownx.snippets:
      base_path: .
      dedent_subsections: true
  - attr_list

exclude_docs: |
  examples-md/*.md
  performance-md/*.md
